version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/poll-app
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=poll-app
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
